/** @type {import('tailwindcss').Config} */
module.exports = {
    darkMode: "class",
    content: ["./index.html", "./src/**/*.{ts,tsx}"],
    theme: {
        extend: {
            colors: {
                "primary-fixed":              "#ffe08e",
                "on-surface":                 "#1b1c19",
                "surface-container-highest":  "#e4e2dd",
                "tertiary":                   "#006c4a",
                "primary-container":          "#e8b800",
                "on-primary-container":       "#5f4a00",
                "secondary-fixed-dim":        "#93ccff",
                "surface-container-low":      "#f5f3ee",
                "surface-container":          "#f0eee9",
                "tertiary-fixed":             "#85f8c4",
                "on-error":                   "#ffffff",
                "tertiary-container":         "#5fd3a1",
                "on-tertiary-container":      "#00593c",
                "secondary-container":        "#5bb8fe",
                "on-surface-variant":         "#4e4633",
                "background":                 "#fbf9f4",
                "outline":                    "#807660",
                "on-tertiary-fixed":          "#002114",
                "inverse-on-surface":         "#f2f1ec",
                "on-tertiary":                "#ffffff",
                "surface-dim":                "#dcdad5",
                "on-tertiary-fixed-variant":  "#005137",
                "on-error-container":         "#93000a",
                "error":                      "#ba1a1a",
                "inverse-surface":            "#30312e",
                "inverse-primary":            "#f1c014",
                "primary":                    "#745b00",
                "outline-variant":            "#d2c5ac",
                "tertiary-fixed-dim":         "#68dba9",
                "on-primary":                 "#ffffff",
                "surface-container-high":     "#eae8e3",
                "on-secondary-container":     "#00476e",
                "error-container":            "#ffdad6",
                "on-primary-fixed":           "#241a00",
                "surface":                    "#fbf9f4",
                "surface-tint":               "#745b00",
                "secondary-fixed":            "#cce5ff",
                "on-secondary-fixed-variant": "#004b73",
                "on-secondary-fixed":         "#001d31",
                "surface-variant":            "#e4e2dd",
                "on-secondary":               "#ffffff",
                "secondary":                  "#006398",
                "on-background":              "#1b1c19",
                "primary-fixed-dim":          "#f1c014",
                "surface-bright":             "#fbf9f4",
                "surface-container-lowest":   "#ffffff",
                "on-primary-fixed-variant":   "#584400",
            },
            borderRadius: {
                DEFAULT: "0.125rem",
                lg:      "0.25rem",
                xl:      "0.5rem",
                full:    "0.75rem",
            },
            fontFamily: {
                headline: ["Inter", "Noto Sans TC", "sans-serif"],
                body:     ["Inter", "Noto Sans TC", "sans-serif"],
                label:    ["Inter", "Noto Sans TC", "sans-serif"],
            },
        },
    },
    plugins: [],
};
